### ISSUE TITLE
Angånde laboration 2

### ISSUE THREAD

**Issue by 1dv449** [sh222td/IDV449-Lab2#1]
Hej!

Vi sitter och går igenom kompletteringar på laborationer men det verkar som vi inte meddelat våra kommentarer kring din rapport/laboration 2 då vi inte hittar att vi satt någon issue här? Är det så att vi missat delge dig detta? Får be om ursäkt för denna miss i så fall. Vet att vi gick igenom din rapport i alla fall. Hur som helst här kommer kommentarer sent om sidor.

Säkerhetsdelen är ok. Kan sakna csrf.
Prestandadelen är lite tunn. Finns mycket mer att skriva om där samt att referenser saknas. Går du igenom den rekommenderade kurslitteraturen kommer du hitta flera punkter. T.ex. HTTP cache headers, minifiering och komprimering av statiska resurser.

Skriv några rader om dessa tre prestandadelar som kommer påverka frontend-delen.

Det finns ett delat dokument där man kan se de olika delar som skulle kunnat tas upp i rapporten.
https://docs.google.com/document/d/1kYNrL64Od1go4z0_sZUyIG8eFAaeFcdp95MIHsRm65A/

**Comment by sh222td** [comment]
Tack så mycket, ska fixa rapporten.

Den 28 dec 2015 09:59 skrev "1dv449" notifications@github.com:

**Comment by sh222td** [comment]
Rapporten är nu kompletterad och finns på mitt repo

https://github.com/sh222td/IDV449-sh222td-Lab2/blob/master/README.md

Den 28 december 2015 10:00 skrev Sandra Hansson sh222td@student.lnu.se:

**Comment by 1dv449** [comment]
Hej! Det är ok nu. Vi stänger denna issue
